#!/usr/bin/env bash

lpstat -s 2>/dev/null | while read -r line ; do
  name="$(echo "$line" | awk -F " " '{print $3}' | tr -d ':')"
  dest="$(echo "$line" | awk -F " " '{print $4}')" 
  if [[ "$dest" == "lpd://10.1.30.48" ]] || [[ "$dest" == "lpd://10.1.30.51" ]] || [[ "$dest" == "ipp://10.1.30.51/" ]] || [[ "$dest" == "ipp://10.1.30.48/" ]] ; then
	lpadmin -x "$name" 
	#echo "$name" 
fi
done



lpadmin -p UMT-Print-East -L UMT-3rd-Fl-East-Printer -E -o printer-is-shared=false -v lpd://10.1.30.51 -P "/Library/Printers/PPDs/Contents/Resources/en.lproj/MP C6004 C4504 E-23C V1.0 US"
lpadmin -p UMT-Print-West -L UMT-3rd-Fl-West-Printer -E -o printer-is-shared=false -v lpd://10.1.30.48 -P "/Library/Printers/PPDs/Contents/Resources/en.lproj/MP C6004 C4504 E-23C V1.0 US"






